// src/angular2/app.component.ts
/**
 * @class AppComponent
 */

import {Component} from '@angular/core';

import {AddTodoComponent} from './components/addtodo.component/addtodo.component';
import {VisibleTodoListComponent} from './components/visibletodolist.component/visibletodolist.component';
import {AppTitleComponent} from './components/apptitle.component/apptitle.component';
import {FilterComponent} from './components/filter.component/filter.component';

@Component({
  directives: [AddTodoComponent,
               VisibleTodoListComponent,
               AppTitleComponent,
               FilterComponent],
  providers: [],
  selector: 'root',
  template: require('./app.component.html'),
})

export class AppComponent {
}

<br/>
<div class="mui-container-fluid">
  <div class="mui-row">
    <div class="mui-col-md-10 mui-col-md-offset-1">
      <div class="mui-panel" style="background-color: #3F51B5; text-align: center;">
        <AppTitle> </AppTitle>
        <AddTodo> </AddTodo>
        <Filter> </Filter>
        <VisibleTodoList> </VisibleTodoList>
      </div>
    </div>
  </div>
</div>

// src/react/components/App.jsx
import React from 'react';
import Row from 'muicss/lib/react/row';
import Col from 'muicss/lib/react/col';
import Panel from 'muicss/lib/react/panel';
import AddTodo from '../containers/AddTodo';
import VisibleTodoList from '../containers/VisibleTodoList';
import AppTitle from './AppTitle';
import Filter from '../containers/Filter';

const App = () => (
  <Row className="mui--text-center">
   <br />
   <Col md="10" md-offset="1">
    <Panel style={{ backgroundColor: '#3F51B5' }}>
      <div>
        <AppTitle color="#FFFFFF" />
        <AddTodo />
        <Filter />
        <VisibleTodoList />
      </div>
    </Panel>
    </Col>
  </Row>
);

export default App;
